export const skills = [
    { name: 'HTML', icon: 'https://mughis.vercel.app/_next/static/media/html.ed6aaa50.svg' },
    { name: 'CSS', icon: 'https://mughis.vercel.app/_next/static/media/css.e5e99f36.svg' },
    { name: 'JavaScript', icon: 'https://mughis.vercel.app/_next/static/media/javascript.b472cbc1.svg' },
    { name: 'TypeScript', icon: 'https://mughis.vercel.app/_next/static/media/typescript.97711300.svg' },
    { name: 'Angular', icon: 'https://th.bing.com/th/id/OIP.Klh1l7wkoG6PDPb9A5oCHQHaHa?rs=1&pid=ImgDetMain' },
    { name: 'React', icon: 'https://mughis.vercel.app/_next/static/media/react.512a3a7e.svg' },
    { name: 'Nextjs', icon: '/public/nextjs-icon.svg' },
    { name: 'Vuejs', icon: '/public/vuejs-icon.svg' },
    { name: 'Firebase', icon: 'https://mughis.vercel.app/_next/static/media/firebase.20c6dcf8.svg' },
    { name: 'Django', icon: 'https://dl.dropboxusercontent.com/scl/fi/lyyqag6bvaa1b1m860if4/django-icon.png?rlkey=pdhlcwyzh3qf9e5375kciljrq&st=bjpfrerx&dl=0' },
    { name: 'Tailwindcss', icon: 'https://mughis.vercel.app/_next/static/media/tailwind.c0bbaf6f.svg' },
    { name: 'MaterialUI', icon: 'https://mughis.vercel.app/_next/static/media/materialui.2900e517.svg' },
    { name: 'Bootstrap', icon: 'https://mughis.vercel.app/_next/static/media/bootstrap.9e6ddba8.svg' },
    { name: 'Git', icon: 'https://mughis.vercel.app/_next/static/media/git.21d80414.svg' },
    { name: 'Framer Motion', icon: 'https://dl.dropboxusercontent.com/scl/fi/gw0a4u08u3y3s0rpuj19u/framer-motion-01.png?rlkey=oo7jketpehqrb39ti105biq8k&st=5lwjf4aq&dl=0' },
    { name: 'Gemini', icon: 'https://dl.dropboxusercontent.com/scl/fi/vqlqua3qapzt7322c0fkv/google-gemini-icon.png?rlkey=z8lnfj8foea2yyhxlw5j0h4qx&st=ltohbna9&dl=0' },
    { name: 'Wordpress', icon: 'https://dl.dropboxusercontent.com/scl/fi/8ebakpy16yrkd6xx0od3p/wordpress.png?rlkey=gpflinqzlpi9i6tc4jm7s6u3b&st=ttve4olw&dl=0' },
    { name: 'Elementor', icon: 'https://dl.dropboxusercontent.com/scl/fi/6p1by38dy4u9r8zxjoalg/elementor.png?rlkey=tcs63ybxx2fnkjzc0250v0808&st=5jruxsho&dl=0' }
  ];